version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - cheon_1_network
    volumes:
      - cheon_1_media:/data/media/
      - cheon_1_static:/data/static/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: cheon_1_django:4
    networks:
      - cheon_1_network
    secrets:
      - DJANGO_SECRET_KEY
    volumes:
      - cheon_1_media:/home/cheon01/media/
      - cheon_1_static:/home/cheon01/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - cheon_1_network
    volumes:
      - cheon_1_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: fkaus132^^
      MARIADB_ROOT_PASSWORD: fkaus132^^

networks:
  cheon_1_network:

volumes:
  cheon_1_media:
  cheon_1_static:
  cheon_1_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true